chats/urls.py
from django.urls import path

from . import views

from django.contrib.auth.views import PasswordChangeView ###




app_name = "chats"

urlpatterns = [
    #path("",views.index, name = "index"),

    path('register/',views.register, name='register'),
    path('follower_register/',views.Follower_register.as_view(), name='follower_register'),
    path('creator_register/',views.Creator_register.as_view(), name='creator_register'),
    path('login/',views.login_request, name='login'),
    path('logout/', views.Logout ,name = 'logout'),
    path('forget-password/' , views.ForgetPassword , name="forget_password"),
    path('change-password/<token>/' , views.ChangePassword , name="change_password"),

  
]

whatsapp_clone/urls.py
from django.contrib import admin
from django.urls import path, include

from chats.views import chat,LandingPageView ,chatPage,search_users , close_session, dashboard
from chats.views import search,login_request,creator_profile, edit_creator_profile, my_profile, delete_chat,follower_profile_edit

from chats.views import user_feedback, feedback_and_rating, callback # ,paymenthandler,

from chats.views import Update_Password, Follower_UserName_Edit      
from payment.views import payment_request

from django.urls import path, re_path, include


from chats.views import FollowerSignupView , CreatorSignupView, LandingPageView

import website.views as website 
from django.urls import path

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('chat/', chat, name='home'),
    path('chat/<int:id>/', chatPage, name='chatPage'),
    path('search/', search_users, name='search_users'),
    path('sea/', search, name = 'search'),
    path('', LandingPageView, name = "landingpage"),
    path("chats/", include("chats.urls")),
    path('accounts/', include('allauth.urls')),
    
    #google login and signup
    path('accounts/signup/Follower/', FollowerSignupView.as_view(), name='Follower_signup'),
    path('accounts/signup/Creator/', CreatorSignupView.as_view(), name='Creator_signup'),
   

        


    path('login/',login_request, name='login_main'),
    
   
    path('profile_edit/', edit_creator_profile, name='edit_creator_profile'),
    path('my_profile/', my_profile, name='my_profile'),
    path('delete_chat/<int:id>/<int:chat_id>' ,delete_chat, name = "delete_chat"),
    path('close_session/<int:id>', close_session, name = 'close_session'),
    path('dashboard', dashboard, name = 'dashboard'),
    path('follower_profile_edit/', follower_profile_edit, name='follower_profile_edit'),
    path('user_feedback/<int:id>/', user_feedback, name='user_feedback'),
    path('rating/', feedback_and_rating, name='feedback_and_rating'),
    path('payment', payment_request, name = "payment_request"),
    # path('paymenthandler/<int:id>', paymenthandler, name = "paymenthandler"),
    path('callback/<int:id>/<int:rid>/', callback, name='callback'),

    path('Follower_UserName_Edit/',Follower_UserName_Edit, name ="Follower_UserName_Edit" ),
    path('Update_Password/',Update_Password, name = "Update_Password"),

    
    path('terms_and_conditions/',website.terms_and_conditions , name = "terms_and_conditions"),
    path('privacy_policy/',website.Privacy_Policy , name = "privacy_policy"),
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
    path('<str:username>/', creator_profile, name='creator_profile'),


]


from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models

# Create your models here.

payments/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render
from django.conf import settings 
# Create your views here.
import razorpay
client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))
    # ...
def payment_request(request):
    
    response = client.order.create({
    'amount': 50000,  # Amount in paise (e.g., ₹500 = 50000 paise)
    'currency': 'INR',
    'payment_capture': '1'  # Auto-capture payments after successful redirection
})
    
    order_id = response['id']
    api_key = "rzp_test_JXDhWdMqazVxVV"


    return render(request, 'payment_form.html', {'order_id': order_id, 'api_key':api_key})

payments/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html>
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    
    </head>

<body>
<main>
    {%block content %} 
    {% endblock content%}
</main>
</body>
</html>

templates/base1.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}{% endblock %}</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" />
    {% block css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}
</body>

</html>

templates/creator_payment_success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link rel="stylesheet" href="/static/css/output.css" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div class="font-bold">
      <div class="text-center font-sans text-2xl font-bold  ">Payment Receieved 🥳</div>
      
      <p>Hello {{Order_obj.Creator.first_name}},</p>
      <div class="ml-4">
      <p>We are thrilled to inform you that a follower has made a payment and is eager to connect with you!</p>
      <p>Payment Amount: ₹{{ Order_obj.amount}}</p>
      <p>To begin the conversation, simply click the button below:</p>
      <p><a class="btn" href="http://127.0.0.1:8000/chat/{{Order_obj.Follower.id}}">Start Conversation</a></p>
      </div>

      <p class="ml-4 pt-2">Best regards,<br />Your Website Team</p>
    </div>
  </body>
</html>

templates/follower_payment_success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!-- <link rel="stylesheet" href="/static/css/output.css" /> -->
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div class="font-bold">
      <h1 class="text-center font-sans text-2xl font-bold">Payment Successful 🥳</h1>
      <p class="font-bold">Dear {{Order_obj.Follower.first_name}},</p>
      <div class="ml-5">
        <p class="">We are pleased to inform you that your payment for Order {{ Order_obj.order_id }} has been successfully processed.</p>
        <p class="">Payment Amount: ${{ Order_obj.amount }}</p>
        <p class="">You can now start a conversation with the creator by clicking the following link:</p>
        <p class=""><a href="http://127.0.0.1:8000/chat/{{Order_obj.Creator.id}}">Start Conversation</a></p>
        <p class="">Thank you for your purchase!</p>
      </div>
      <p class="">Sincerely,<br />Your Website Team</p>
    </div>
  </body>
</html>

templates/follower_register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Follower Sign up</title>
    {% load widget_tweaks %}
    <!-- Link the Tailwind CSS stylesheet -->
    <!-- <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" />
     -->
    <link href="/static/css/output.css"  rel="stylesheet"/>
  
  </head>

  <body>
        
    <div class="h-14 flex items-center px-4 w-full bg-[#00002E]">

        
      <span id = "goBackButton">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="fill-current text-[#caf0f8] mr-4 w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75" />
        </svg>
      </span>
    
    <h1 class="text-[#caf0f8] text-lg font-bold " >Sign up as Follower</h1>
    
    </div>


    <div class="flex min-h-screen items-center justify-center bg-[#caf0f8]">
      
      <div class="w-full md:max-w-sm rounded-lg bg-[#caf0f8] p-8 shadow-2xl">
        <h1 class="mb-6 text-center text-2xl font-bold text-[#00002E]">Sign up as Follower </h1>

        <form action="{% url 'chats:follower_register' %}" method="POST" novalidate>
          {% csrf_token %}
          <!-- Username Label and Input -->
          <div class="mb-4">  
            <!-- <label for="username" class="mb-2 block text-sm font-medium text-gray-300">Username</label> -->
            <!-- <input type="text" id="username" name="username" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your username" required /> -->
            {% render_field form.username type="text" id="username" name="username" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your username" %}
            
            {% for error in form.username.errors %}
              <span class="text-red-600">{{ error }}</span>
            {% endfor %}

          </div>


          <!-- Name Label and Input -->
          <div class="mb-4 ">
            <!-- <label for="name" class="mb-2 block text-sm font-medium text-gray-300">Name</label> -->
            <!-- <input type="text" id="name" name="name" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your name" required /> -->
            {% render_field form.first_name type="text" id="name" name="name" class="w-full  rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your name" %}
            
            {% for error in form.first_name.errors %}
              <span class="text-red-600">{{ error }}</span>
            {% endfor %}
          </div>

          <!-- Email Label and Input -->
          <div class="mb-4 ">
            <!-- <label for="email" class="mb-2 block text-sm font-medium text-gray-300">Email</label> -->
            <!-- <input type="email" id="email" name="email" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your email" required /> -->
            {% render_field form.email type="email" id="email" name="email" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your email" %}
            
            {% for error in form.email.errors %}
              <span class="text-red-600">{{ error }}</span>
            {% endfor %}
          </div>

          <!-- Password Label and Input -->
          <div class="mb-4 ">
            <!-- <label for="password" class="mb-2 block text-sm font-medium text-gray-300">Password</label> -->
            <!-- <input type="password" id="password" name="password" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your password" required /> -->
            {% render_field form.password1 type="password" id="password" name="password" class="w-full  rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your password" %}
            {% for error in form.password1.errors %}
              <span class="text-red-600">{{ error }}</span>
            {% endfor %}
          </div>

          <div class="mb-4 ">
            <!-- <label for="password" class="mb-2 block text-sm font-medium text-gray-300">Confirm Password</label> -->
            <!-- <input type="password" id="password" name="password" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your password" required /> -->
            <div class="relative"> 
            {% render_field form.password2 type="password" id="confirm_password" name="password" class="w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Re-enter your password" %}
            <span class="text-slate-600 text-sm absolute top-1/2 right-3 transform -translate-y-1/2 cursor-pointer" onclick="togglePasswordVisibility()">
              <svg id="ShowPassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>

            <svg id="HidePassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="hidden w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
            </svg>
            
            </span>
            </div>
            
            {% for error in form.password2.errors %}
              <span class="text-red-600">{{ error }}</span>
            {% endfor %}
          </div>

             

          
          
          <!-- Sign Up Button -->
          <button type="submit" class="mt-2 mb-4 w-full rounded-lg bg-blue-500 px-4 py-2 font-bold text-white transition duration-300 hover:bg-blue-600">Sign Up</button>
        </form>
       
       

        <h1 class="py-4 text-center text-[#00002E]">Have an Account ? <a href = "{% url 'chats:login' %}"class="text-blue-400">Log in</a></h1>
      

        <!-- Login with Google Button -->
        
          {% load socialaccount %}
          {% block content %}
                <div class="flex  justify-center ring-1 hover:bg-gray-500 bg-gray-400 rounded-xl ring-gray-400">
                  <div class="col-md-3 px-4 py-1 ">
                    <a class="btn btn-outline-dark" href="{% provider_login_url 'google' %}" role="button" style="text-transform: none; display: flex; align-items: center;">
                      <div>
                          <img width="20px" style="margin-bottom: 3px; margin-right: 5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
                      </div>
                      <div class="mb-1 font-semibold px-4">Login with Google</div>
                  </a>
                  </div>
                </div>
            {% endblock content %}
        


      </div>
      
    </div>
  </body>
</html>
<script>

  ////
   document.getElementById('goBackButton').addEventListener('click', function () {
        window.history.back();
    });


     ///////Show Password and hide Password section//////////////////

     function togglePasswordVisibility() {
      var passwordInput = document.getElementById("confirm_password");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            document.getElementById("ShowPassword").classList.add("hidden");
            document.getElementById("HidePassword").classList.remove("hidden");
        } else {
            passwordInput.type = "password";
            document.getElementById("HidePassword").classList.add("hidden");
            document.getElementById("ShowPassword").classList.remove("hidden");
        }
    }
        
    ////////End of Show Password and Hide Password section////////////
</script>

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Login Page</title>
    <!-- Link the Tailwind CSS stylesheet -->
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" /> -->
    <link href="/static/css/output.css"  rel="stylesheet"/>
    {% load socialaccount %}



  </head>

  <body>

    <div class="h-14 flex items-center px-4 w-full bg-[#00002E]">

        
      <span id = "goBackButton">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="fill-current text-[#caf0f8] mr-4 w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75" />
        </svg>
      </span>
    
    <h1 class="text-[#caf0f8] text-lg font-bold " >Login</h1>
    
  </div>
  
    <div class="flex min-h-screen items-center justify-center bg-[#caf0f8]">
      <div class="w-full max-w-sm rounded-lg bg-[#caf0f8] p-8 shadow-md">
        <h1 class="mb-6 text-center text-2xl font-bold text-[#00002E]">Login</h1>

        <form action="{% url 'chats:login' %}" method="POST" novalidate>
            {% csrf_token %}
          <!-- Email/Username Label -->
          <!-- <label for="email" class="mb-2 block text-sm font-medium text-[#00002E]">Email or Username</label> -->
          <input type="text" id="email" name="email" class="mb-4 w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your email or username" required />
          {% for error in form.first_name.errors %}
          <span class="text-red-600">{{ error }}</span>
            {% endfor %}
          <!-- Password Label -->
          <!-- <label for="password" class="mb-2 block text-sm font-medium text-gray-500">Password</label> -->
          <div class="relative">
            <input type="password" id="password" name="password" class=" w-full rounded-lg border px-3 py-2 focus:border-blue-300 focus:outline-none focus:ring" placeholder="Enter your password" required />
            <span class="text-slate-600 text-sm absolute top-1/2 right-3 transform -translate-y-1/2 cursor-pointer" onclick="togglePasswordVisibility()">
              <svg id="ShowPassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>

            <svg id="HidePassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="hidden w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
            </svg>
            
            </span>
          </div>
          {% for error in form.first_name.errors %}
          <span class="text-red-600">{{ error }}</span>
            {% endfor %}

          {% if messages %}                          
            {% for message in messages %}
              <h1 class="pb-4 text-red-600">{{ message }} </h1>
            {% endfor %}
          {% endif %}
          <!-- messages  -->

          
          
          


          <!-- Login Button -->
          <button type="submit" class="w-full font-bold rounded-xl bg-blue-500 px-4 py-2 text-white transition duration-300 hover:bg-blue-600">Login</button>
        </form>

        <!-- forgot Password -->
        <a href="{% url 'chats:forget_password' %}"><p class=" pt-4 text-center text-blue-400 hover:text-blue-600">Forgot password ?</p></a>

        <!-- OR Separator -->
        <div class="flex my-4 items-center justify-center">
          <div class="w-full border-t border-gray-400"></div>
          <div class="px-3 text-gray-500">OR</div>
          <div class="w-full border-t border-gray-400"></div>
        </div>

          <!-- Login with Google Button -->
     
          {% block content %}
                <div class="flex  justify-center ring-1 hover:bg-gray-400 bg-gray-400 rounded-xl ring-gray-400">
                  <div class="col-md-3 px-4 py-1 ">
                    <a class="btn btn-outline-dark" href="{% provider_login_url 'google' %}" role="button" style="text-transform: none; display: flex; align-items: center;">
                      <div>
                          <img width="20px" style="margin-bottom: 3px; margin-right: 5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
                      </div>
                      <div class="mb-1 font-semibold px-4">Login with Google</div>
                  </a>
                  </div>
                </div>
                
            {% endblock content %}
      
    

          
          
                    
        <!-- Other links, forgot password, etc. can be added here -->

        <h1 class="mt-4 text-center font-semibold text-[#00002E]"> Don't have an account ? <a href = "{% url 'chats:register' %}" class="font-semibold hover:text-blue-600 text-blue-400"> Sign up </a></h1>
      </div>
     
    </div>
    
  </body>
</html>
<script>
     ///////Show Password and hide Password section//////////////////

     function togglePasswordVisibility() {
      var passwordInput = document.getElementById("password");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            document.getElementById("ShowPassword").classList.add("hidden");
            document.getElementById("HidePassword").classList.remove("hidden");
        } else {
            passwordInput.type = "password";
            document.getElementById("HidePassword").classList.add("hidden");
            document.getElementById("ShowPassword").classList.remove("hidden");
        }
    }


        /// Go Back Functionality
        document.getElementById('goBackButton').addEventListener('click', function () {
        window.history.back();
    });
</script>

templates/payment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>

</head>
<body>
    
    <button id="rzp-button1">Pay</button>

<script>
var options = {
    "key": "{{api_key}}", // Enter the Key ID generated from the Dashboard
    "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Acme Corp", //your business name
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "https://eneqd3r9zrjok.x.pipedream.net/",
    "prefill": { //We recommend using the prefill parameter to auto-fill customer's contact information especially their phone number
        "name": "Gaurav Kumar", //your customer's name
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000" //Provide the customer's phone number for better conversion rates 
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
</body>
</html>